### ISSUE TITLE
How to Print Received Message In NSLog.....

### ISSUE THREAD

**Issue by bnagarjuna** [kudocc/simpleServer#1]
In NSLog only Print Message Length...

read from socket len 82
success write 82

Please Help How to Print Message in Log.......

**Comment by kudocc** [comment]
You can find the solution in [cfnetwork](https://github.com/kudocc/tcpClient/blob/master/cfnetwork/KDConnection.mm)

**Comment by kudocc** [comment]
Fix it in #61a88911a840
